jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python27:
        PYTHON_VERSION: '2.7'
      Python34:
        PYTHON_VERSION: '3.4'
      Python35:
        PYTHON_VERSION: '3.5'
      Python36:
        PYTHON_VERSION: '3.6'
      Python37:
        PYTHON_VERSION: '3.7'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
      architecture: 'x64'
    displayName: 'Install Python'
  - script: |
      make
      pipenv install -e .[socks] --skip-lock
    displayName: 'Set up'

  - ${{ if eq(parameters.name, 'Linux') }}:
    - script: |
        make test-readme
        make ci
      displayName: 'Test and CI'
    - task: PublishTestResults@2
      displayName: 'Publish test results'
      inputs:
        testResultsFiles: 'report.xml'
        testRunTitle: Python $(PYTHON_VERSION)

  - script: |
      pipenv run codecov -f coverage.xml
    displayName: 'Run codecov'
